### ISSUE TITLE
Licensing?

### ISSUE THREAD

**Issue by polymeris** [andeemarks/clj-hex-grid#2]
LICENSE says MIT
README says EPL

**Comment by polymeris** [comment]
BTW, project.clj says EPL, as well

**Comment by andeemarks** [comment]
Hi Camilo,

I've standardised on EPL.

Cheers,
Andy

_Andy MARKS_
_Office Principal_
ThoughtWorks Melbourne
_mobile: *0435 318 616
*email_: amarks@thoughtworks.com
_web_: www.thoughtworks.com
